name: Scripting in Github actions 
run-name: "Scripting in Github actions @${{github.actor}}"
on: 
  workflow_dispatch:
    inputs: 
      os: 
        description: Operating Systems
        default: "windows-latest, ubuntu-latest, macos-latest"
        type: string

jobs:
  Scripting:
    runs-on: ubuntu-latest
    steps:
      - name: Use github-script action 
        id: script-id
        uses: actions/github-script@v6
        whith:
          script: |
            "return {OS: context.payload.inputs['os'].split(',')}"
            result-encoding: json
      - name: Echo script ID 
        run: |
          echo "step script-output=value" >> $GITHUB_OUTPUT
          cat ${{steps.script-id.outputs}}